### ISSUE TITLE
Unfurl images 

### ISSUE THREAD

**Issue by portdeveloper** [BuidlGuidl/abi.ninja#89]
## Unfurl Images

Working on an unfurl images feature.
This is the branch: [https://github.com/BuidlGuidl/abi.ninja/tree/feat/unfurls](https://github.com/BuidlGuidl/abi.ninja/tree/feat/unfurls)

### Test the feature

clone the repo

run `yarn start`

Go to the following link:
[http://localhost:3001/api/og?contractAddress=0x514910771af9ca656af840dff83e8264ecf986ca&network=1
](http://localhost:3001/api/og?contractAddress=0x514910771af9ca656af840dff83e8264ecf986ca&network=1
)

### Expected look: 
![image](https://github.com/BuidlGuidl/abi.ninja/assets/108868128/7571762a-433e-4391-870a-beb3c6bfb8be)

The problem is that we are getting the following error as soon as I try to add a `publicClient `from `viem `in `api/og.tsx`:
![image](https://github.com/BuidlGuidl/abi.ninja/assets/108868128/de99839d-f6fa-44e8-ac5b-ba8576e170be)

`error - PageNotFoundError: Cannot find module for page: /api/og
    at DevServer.getEdgeFunctionInfo (C:\Users\port\repos\production\abi.ninja\packages\nextjs\node_modules\next\dist\server\next-server.js:1429:23)
    at DevServer.runEdgeFunction (C:\Users\port\repos\production\abi.ninja\packages\nextjs\node_modules\next\dist\server\next-server.js:1857:25)
    at DevServer.runEdgeFunction (C:\Users\port\repos\production\abi.ninja\packages\nextjs\node_modules\next\dist\server\dev\next-dev-server.js:872:26)
    at Object.fn (C:\Users\port\repos\production\abi.ninja\packages\nextjs\node_modules\next\dist\server\next-server.js:1104:70)  
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Router.execute (C:\Users\port\repos\production\abi.ninja\packages\nextjs\node_modules\next\dist\server\router.js:315:32)
    at async DevServer.runImpl (C:\Users\port\repos\production\abi.ninja\packages\nextjs\node_modules\next\dist\server\base-server.js:604:29)
    at async DevServer.run (C:\Users\port\repos\production\abi.ninja\packages\nextjs\node_modules\next\dist\server\dev\nrver.js:922:20)
    at async DevServer.handleRequestImpl (C:\Users\port\repos\production\abi.ninja\packages\nextjs\node_modules\next\dist\server\base-server.js:533:20) {
  code: 'ENOENT',
  message: 'Cannot find module for page: Cannot find module for page: /api/og',
  digest: undefined`

### What I did to solve the problem (temporarily)

Since the feature was working in `address.vision`, I downgraded some crucial packages to the versions we use in address.vision in the following PR:
[https://github.com/BuidlGuidl/abi.ninja/pull/88/commits/8ea6bcf855f25d8f58f565e3701e1a3bbf315711](https://github.com/BuidlGuidl/abi.ninja/pull/88/commits/8ea6bcf855f25d8f58f565e3701e1a3bbf315711)

After the changes in the PR, it worked but vercel couldn't deploy the app.
Logs:
[https://github.com/BuidlGuidl/abi.ninja/actions/runs/8813164540/job/24190329420?pr=88](https://github.com/BuidlGuidl/abi.ninja/actions/runs/8813164540/job/24190329420?pr=88)

Some info that @technophile-04 has found:
[https://github.com/wevm/viem/discussions/368](https://github.com/wevm/viem/discussions/368)
[https://github.com/replicate/replicate-javascript/issues/225#issuecomment-2065499818](https://github.com/replicate/replicate-javascript/issues/225#issuecomment-2065499818)

Will soon create a nextjs app and add everything there from scratch and see if it works. Let me know what you think of this problem!

**Comment by technophile-04** [comment]
Completed at #90
